### ISSUE TITLE
Pinned callout blocks lose data.

### ISSUE THREAD

**Issue by rafegoldberg** [readmeio/markdown#35]
|[Asana](https://app.asana.com/0/681252538274980/1173787416619689/f)|
|:---:|

In certain scenarios when a callout is pinned to the sidebar, like so...

![image](https://user-images.githubusercontent.com/886627/80780012-3e624d00-8b22-11ea-9777-e2fb9ac24e2a.png)

...it seems to loose it's content on render:

![image](https://user-images.githubusercontent.com/886627/80779945-09ee9100-8b22-11ea-8753-195d6c26c732.png)

This is likely to do with the way I've set up the callout AST, which requires some hoop-thru-jumping to parse out the icon and title text from the rest of the `children` content:

https://github.com/readmeio/api-explorer/blob/2cfc9160a46293b07574d49c2a255f783afd1a90/packages/markdown/components/Callout/index.jsx#L18

**Comment by kellyjosephprice** [comment]
I'm closing this as I believe it is now fixed!
