### ISSUE TITLE
React processor throws "ReferenceError: process is not defined"

### ISSUE THREAD

**Issue by inv8der** [readmeio/markdown#495]
Hello 👋 

I'm trying to render some markdown content that I retrieved via the ReadMe API. My setup is pretty simple. Based off the example from the README, I have:

```typescript
import rdmd from '@readme/markdown';

export interface Props {
  body?: string;
}

export default function Markdown({ body }: Props) {
  return <div className="markdown-body">{rdmd(body)}</div>;
}
```

In my project, when I render the `Markdown` component, I see the following error in the console:

![Screen Shot 2022-05-11 at 12 01 37 PM](https://user-images.githubusercontent.com/830026/167926054-8efc2e21-2c2a-4a49-ab52-bf2039d1b648.png)

I did some digging, and it looks like the version of `vfile` that gets rolled up into the build is at `4.1.1`. In version [`4.2.1`]( https://github.com/vfile/vfile/releases/tag/4.2.1), they added manual browser polyfills for path and process. I know I could change my webpack config to resolve the issue, but it'd be nice if this package was updated to pull in a newer version of `vfile`. All that would be needed is to run `npm update vfile` to update the resolved version in `package-lock.json`.

**Comment by rafegoldberg** [comment]
<img align="right" height="100" src="https://user-images.githubusercontent.com/886627/87183626-529d9580-c29b-11ea-8c54-5ca58a1f4a77.png" />

## This issue was resolved!

🚀 Changes included in [<b>v6.41.0</b>](/readmeio/markdown/releases/tag/v6.41.0)
<br>
