### ISSUE TITLE
Module not found: Can't resolve '@readme/variable'

### ISSUE THREAD

**Issue by brianwachira** [readmeio/markdown#534]
I installed the package on my nextjs 12, typescript 4.7.4 and tailwind 3.1.4 project. On initialising using the package, I get this error

> error - ./node_modules/@readme/markdown/dist/main.js:3:0
Module not found: Can't resolve '@readme/variable'

![image](https://user-images.githubusercontent.com/28436092/178978414-9e2d1827-a210-401d-8b37-3f919dfb1578.png)

Here is my code snippet

![image](https://user-images.githubusercontent.com/28436092/178979818-9c554f0a-e2ba-432c-9363-f15adde28e66.png)

there's a red highlight on the code blocks but it shouldn't affect whether my code runs or not. 
Please help,otherwise, I will have to look for some other way to present code blocks in tabs

**Comment by erunion** [comment]
👋 Which version of NPM are you using? `@readme/variable` is listed as a peer dependency of this package and NPM versions less than 6 don't install them by default.

**Comment by beneliflo** [comment]
Hi @erunion! same @brianwachira 's package intstalled in my project and same error. My npm version is 8.5.5

**Comment by beneliflo** [comment]
@brianwachira you can fix it by installing it on your end.

**Comment by brianwachira** [comment]
> wave Which version of NPM are you using? `@readme/variable` is listed as a peer dependency of this package and NPM versions less than 6 don't install them by default.

I am using npm v 8.3.2

**Comment by rafegoldberg** [comment]
<img align="right" height="100" src="https://user-images.githubusercontent.com/886627/87183626-529d9580-c29b-11ea-8c54-5ca58a1f4a77.png" />

## This issue was resolved!

🚀 Changes included in [<b>v6.47.0</b>](/readmeio/markdown/releases/tag/v6.47.0)
<br>
