### ISSUE TITLE
Syntax for setting up code blocks in nextjs & typescript

### ISSUE THREAD

**Issue by brianwachira** [readmeio/markdown#541]
Hi there, I am using this package on my **nextjs v12.2.0** , **react v18.2.0**, **typescript v4.7.4** project. **Node v14.17.0**, **npm v8.3.2**
I have copy pasted the syntax found in the [docs](https://rdmd.readme.io/docs/code-blocks#syntax)
![image](https://user-images.githubusercontent.com/28436092/179698021-14d45c40-e327-4a41-b021-cca64d72573f.png)

Here is my code
![image](https://user-images.githubusercontent.com/28436092/179698336-d28bec8d-2b12-4820-b0e2-bc7eac2088ce.png)

It shows a typescript error. When I hover over the area there's an error this is what I get
 
![Screenshot from 2022-07-19 10-59-53](https://user-images.githubusercontent.com/28436092/179699127-5602d659-a2f5-4f3c-a7d1-0642930205d0.png)

What is the correct syntax for setting up code blocks markdown in nextjs and typescript

**Comment by kellyjosephprice** [comment]
I would recommend:

```
const body = `
\`\`\`
console.log('Code Tab A');
\`\`\`
\`\`\`
console.log('Code Tab B');
\`\`\`
`;
```

I've done a few things:

1. Wrapped the markdown snippet in backticks (`) to create a [template string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). I believe normal strings don't support multi-line strings.

2. Escape the backticks in the markdown snippet, that way they don't close or start new template strings.

**Comment by brianwachira** [comment]
> I would recommend:
> 
> ```
> const body = `
> \`\`\`
> console.log('Code Tab A');
> \`\`\`
> \`\`\`
> console.log('Code Tab B');
> \`\`\`
> `;
> ```
> 
> I've done a few things:
> 
>     1. Wrapped the markdown snippet in backticks (`) to create a [template string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). I believe normal strings don't support multi-line strings.
> 
>     2. Escape the backticks in the markdown snippet, that way they don't close or start new template strings.

It worked. Thanks! 
Closing this issue
