### ISSUE TITLE
Should tabbed code blocks allow indentation?

### ISSUE THREAD

**Issue by kellyjosephprice** [readmeio/markdown#76]
The commonmark [spec for code blocks](https://spec.commonmark.org/0.29/#fenced-code-blocks) allows indentation for code blocks. I'm pretty sure our implementation for tabbed code blocks does not.

**Comment by rafegoldberg** [comment]
The engine does indeed support indented syntax for code blocks. (By way of example, note that [this syntax](https://dash.readme.com/project/rdmd/v1.2.0/docs/indented-code) correctly [renders a code block](https://rdmd.readme.io/docs/indented-code)!)
